apiVersion: v1
kind: Service
metadata:
  name: v1-service
spec:
  selector:
    app: v1
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: v2-service
spec:
  selector:
    app: v2
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http